# Generated by Django 3.2.9 on 2022-01-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_app', '0004_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='snippet', max_length=200),
        ),
    ]
