# Generated by Django 4.0.5 on 2022-06-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_app', '0005_post_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='datails_na',
            new_name='details_na',
        ),
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(max_length=200),
        ),
    ]
