# Generated by Django 4.0.5 on 2022-07-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_app', '0010_rename_comment_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
